
name: Build Debian loong64 kernel

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    runs-on: self-hosted
    name: Build loong64 kernel
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: deepin-community/kerne
          ref: linux-6.12.y
          fetch-depth: 1
          submodules: recursive 
          path: 'linux'
              
      - name: Build Linux kernel
        run: |
          cd linux
          # Build deb
          make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- deepin_loongarch_desktop_defconfig
          make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- bindeb-pkg -j$(nproc)

          # Prepare artifact
          cd ..
          mkdir -p assets/ && mv ./*.deb assets/

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: loong64 kernel for Debian
          path: assets/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`