
name: Build Debian loong64 kernel

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    runs-on: self-hosted
    name: Build loong64 kernel
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: deepin-community/kernel
          ref: linux-6.12.y
          fetch-depth: 1
          submodules: recursive 
          path: 'linux'
              
      - name: Build Linux kernel
        run: |
          cd linux
          rm -rf init/build-version
          cat <<EOF >> init/build-version
          #!/bin/sh
          # SPDX-License-Identifier: GPL-2.0-only

          prev_ver=$(cat .version 2>/dev/null) &&
          ver=$(expr ${prev_ver} + 1 2>/dev/null) ||

          # Respect $prev_ver as the final build version ID.
          if [ X$prev_ver = "X" ]
          then
            ver=1
          else
            ver=$prev_ver
          fi
          echo ${ver} > .version

          echo ${ver}

          EOF
          chmod +x init/build-version

          # Build deb
          make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- deepin_loongarch_desktop_defconfig
          make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- bindeb-pkg -j$(nproc)

          # Prepare artifact
          cd ..
          mkdir -p assets/ && mv ./*.deb assets/

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: loong64 kernel for Debian
          path: assets/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`